-include .env
deploy-sepollia-test:dotenv forge test --fork-url "$(SEPOLIA_RPC_URL)"

deploy-sepolia:
	forge script script/DeployfundMe.s.sol:DeployFundMe --rpc-url $(SEPOLIA_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHERSCAN_API_KEY) -vvvv	